### ISSUE TITLE
关于检测学校网站可用性

### ISSUE THREAD

**Issue by Thehrz** [cokice/List-of-genshin-University#107]
由于学校网站使用了 WAF 服务，屏蔽了 IDC IP 的访问，使得 Github Actions 无法访问。

本人的跳转服务是没有问题的，普通用户在正常情况也能访问跳转。

https://github.com/cokice/List-of-genshin-University/actions/runs/8405250821/job/23017728174#step:6:311

```text
Checking [https://中国原神中学.com]... A to [47.242.166.174] Redirect to [https://www.hfbz.com/] with status code 301
-- Checking redirect... Checking [https://www.hfbz.com/]... CNAME to [8s8tzkziqoystgpuctkzi8ffmdohh4kp.yundunwaf1.com] Failed with status code 405
Failed, trying other possible URLs
```

[https://www.hfbz.com/](https://www.hfbz.com/) 是学校的网站。高中学校域名也不是 .edu.cn 结尾，故不能跳过检测。

建议做白名单，使用正则表达式匹配，包含 .edu.cn 还有像这样的网站域名。

**Comment by CarlGao4** [comment]
白名单考虑添加
不过因为第一步可以访问，所以状态是❓，这种情况视为可以访问，也在文档中说了

**Comment by CarlGao4** [comment]
已经更新白名单。
