### ISSUE TITLE
关于301重定向 被云服务器运营商阻断

### ISSUE THREAD

**Issue by sileence114** [cokice/List-of-genshin-University#15]
要怎么申请备案？说整活？还是说这种情况只能选国外的云服务提供商了？

**Comment by wangcham** [comment]
建议国外，或者描述写生活笔记，只要动静不大一般都不会有事

**Comment by cz-kaga** [comment]
我用的是https://www.redirhub.com/，有免费的转发额度
建议用302转，301会被浏览器永久缓存，之后改不了（
