### ISSUE TITLE
宜宾学院

### ISSUE THREAD

**Issue by Gloridust** [cokice/List-of-genshin-University#44]
位于四川省宜宾市的：宜宾学院
域名采用全中文域名：https://原神学院.中国

采用cloudflare works反向代理，有一半的概率打不开。若打不开，请多刷新几次。

**Comment by cokice** [comment]
已添加

**Comment by ChrisYH20** [comment]
目前代理已被防火墙拦截![image](https://github.com/cokice/List-of-genshin-University/assets/140259582/79a377d2-477b-4111-89f0-6910aa5c3937)

**Comment by Gloridust** [comment]
> 目前代理已被防火墙拦截![image](https://github.com/cokice/List-of-genshin-University/assets/140259582/79a377d2-477b-4111-89f0-6910aa5c3937)

很抱歉出现这个问题，可能是学校察觉了异常镜像解析手段，然后提高了防火墙水平。稍后我尝试一下修复。
