### ISSUE TITLE
www.原神启动.com 信息错误

### ISSUE THREAD

**Issue by Eternal973** [cokice/List-of-genshin-University#81]
现在是元梦之星官网……是否考虑制作动态检测连通性和跳转后url的页面？

**Comment by Eternal973** [comment]
跳转后url要检测感觉有点麻烦，大家实现跳转的方法各有不同，有的是302有的是打开网页再跳的

**Comment by CarlGao4** [comment]
还有直接CNAME的

**Comment by cokice** [comment]
这个真还无法检测出来呢 最多只能知道这些网站能不能连通

**Comment by CarlGao4** [comment]
我感觉应该有办法，利用GitHub Actions，调用webdriver访问这些网站，等待特定时间（比如30秒）后去读去网页的<head>里面元数据和页面标题，判断跳转地址
