### ISSUE TITLE
关于 Github Action 没权限问题

### ISSUE THREAD

**Issue by th1nk-er** [cokice/List-of-genshin-University#88]
在仓库设置中，给予github action workflow 的读写权限
Settings -> Action -> General -> Workflow permissions  **read and write permissions**

或者

在工作流文件中增加写的权限
runs-on: ubuntu-latest
permissions:
  contents: write

**Comment by cokice** [comment]
我试一下 刚刚一直纳闷怎么跑不通

**Comment by cokice** [comment]
可以了 非常感谢你的脚本
