### ISSUE TITLE
更准确的检测可用性的方法

### ISSUE THREAD

**Issue by CarlGao4** [cokice/List-of-genshin-University#90]
目前还不成熟，还在测试有没有更好的办法
已经添加的功能：尝试其他可能的域名、添加代理
可参考https://github.com/CarlGao4/List-of-genshin-university

**Comment by th1nk-er** [comment]
思路：可以使用站长工具以国内IP查询
[HTTP状态查询](https://tool.chinaz.com/pagestatus/)
